WebApplication4/Models/Pendant.cs
using System.Web.UI.HtmlControls;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace WebApplication4.Models
{
    public class Pendant
    {
        [Key]
        public int Id { get; set; }
        public decimal Price { get; }
        public string Description { get; set; }
        public Size PendantSize { get; set; }
        public string PendantImage { get; set; }
        public HttpPostedFileBase UploadedFile { get; set; }
    }

    public enum Size
    {
        Small,
        Medium,
        Large
    }
}

WebApplication4/Models/PendantProduct.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication4.Models
{
    public class PendantProduct
    {
        [Key]
        public int Id { get; set; }
        public decimal Price { get; }
        public string Description { get; set; }
        public Size PendantSize { get; set; }
        public string FileName { get { return Id + ".jpg"; } }

        [NotMapped]
        public HttpPostedFileBase UploadedFile { get; set; }
    }
}

WebApplication4/Models/PendantProductContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebApplication4.Models
{
    public class PendantProductContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public PendantProductContext() : base("name=PendantProductContext")
        {
        }

        public System.Data.Entity.DbSet<WebApplication4.Models.PendantProduct> PendantProducts { get; set; }
    }
}

WebApplication4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication4/Controllers/PendantProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class PendantProductsController : Controller
    {
        private PendantProductContext db = new PendantProductContext();

        // GET: PendantProducts
        public async Task<ActionResult> Index()
        {
            return View(await db.PendantProducts.ToListAsync());
        }

        // GET: PendantProducts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PendantProduct pendantProduct = await db.PendantProducts.FindAsync(id);
            if (pendantProduct == null)
            {
                return HttpNotFound();
            }
            return View(pendantProduct);
        }

        // GET: PendantProducts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PendantProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Description,PendantSize")] PendantProduct pendantProduct)
        {
            if (ModelState.IsValid)
            {
                db.PendantProducts.Add(pendantProduct);
                await db.SaveChangesAsync();
                
                if (pendantProduct.UploadedFile != null)
                    pendantProduct.UploadedFile.SaveAs(Path.Combine("App_Data", pendantProduct.FileName));

                return RedirectToAction("Index");
            }

            return View(pendantProduct);
        }

        // GET: PendantProducts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PendantProduct pendantProduct = await db.PendantProducts.FindAsync(id);
            if (pendantProduct == null)
            {
                return HttpNotFound();
            }
            return View(pendantProduct);
        }

        // POST: PendantProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Description,PendantSize")] PendantProduct pendantProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pendantProduct).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");

               
            }
            return View(pendantProduct);
        }

        // GET: PendantProducts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PendantProduct pendantProduct = await db.PendantProducts.FindAsync(id);
            if (pendantProduct == null)
            {
                return HttpNotFound();
            }
            return View(pendantProduct);
        }

        // POST: PendantProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            PendantProduct pendantProduct = await db.PendantProducts.FindAsync(id);
            db.PendantProducts.Remove(pendantProduct);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication4/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>We make shit for you if you pay us.</p>

WebApplication4/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Ben's House<br />
    La Grange Park, IL 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    708.420.5768
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Peoples Personal Pendants</h1>
    <p class="lead">We make pendants for money!</p>
    <p><a href="" class="btn btn-primary btn-lg">Pay Us! &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Give us money and a design and we'll give you pendant
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">You know enough &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more Pendants</h2>
        <p>If you bought one and would like another, just buy another one.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Pendant Hosting</h2>
        <p>We don't do that.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication4/Views/PendantProducts/Create.cshtml
@model WebApplication4.Models.PendantProduct

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PendantProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PendantSize, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PendantSize, htmlAttributes: new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.PendantSize, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UploadedFile, htmlAttributes: new {@class = "control-label col-md-2" } )
            <div class="col-md-10">
                <input type="file" enctype = "multipart/form-data" name="picture"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication4/Views/PendantProducts/Delete.cshtml
@model WebApplication4.Models.PendantProduct

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PendantProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PendantSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PendantSize)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication4/Views/PendantProducts/Details.cshtml
@model WebApplication4.Models.PendantProduct

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PendantProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PendantSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PendantSize)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication4/Views/PendantProducts/Edit.cshtml
@model WebApplication4.Models.PendantProduct

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PendantProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PendantSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PendantSize, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PendantSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication4/Views/PendantProducts/Index.cshtml
@model IEnumerable<WebApplication4.Models.PendantProduct>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PendantSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UploadedFile)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PendantSize)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Peoples Personal Pendants</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Peoples Personal Pendants", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Pendants", "Index", "PendantProducts")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Peoples Personal Pendants</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>